# ==============================================================================
# PROJECT METADATA
# ==============================================================================

name: spinify_clock_frontend

description: "Spinify Clock: Frontend"

publish_to: 'none'

version: 0.0.1+1

homepage: https://github.com/plugfox/spinify

repository: https://github.com/plugfox/spinify

issue_tracker: https://github.com/plugfox/spinify/issues

#funding:
#  -

#topics:
#  -

platforms:
  web:

#screenshots:
#  - description: 'Screenshot 1'
#    path: screenshot_1.png


# ==============================================================================
# PROJECT STRUCTURE
# ==============================================================================

# https://dart.dev/tools/pub/workspaces
#workspace:
#  - ../shared

#executables:
#  -


# ==============================================================================
# DEPENDENCIES
# ==============================================================================

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  # Localization
  intl: ^0.20.2

  # Annotation
  l: ^5.0.0
  meta: any

  # Web
  web: ^1.1.0

dev_dependencies:
  # Linting
  lints: ^5.1.1

  # Testing
  test: any

  # Code generation
  build_runner: ^2.4.13
  build_web_compilers: ^4.1.1
